### pandas

In [3]:
import numpy as np
np.random.normal(60,5,(25))

array([56.41176045, 53.89890641, 64.59845249, 62.14790801, 60.99878701,
       58.81304213, 64.75678645, 56.26337855, 63.49761997, 62.45762258,
       71.31826167, 60.91095105, 62.36847473, 58.34483581, 62.33431471,
       67.72960031, 57.11808798, 65.88259738, 64.93808496, 57.57422907,
       58.46954833, 63.76625819, 53.7868815 , 53.19796308, 63.99890709])

In [4]:
import pandas as pd

In [5]:
pd.__version__

'2.3.1'

In [6]:
df = pd.read_csv('iris.csv')

In [34]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head() #df.head() : 첫 부분(기본적으로 5개 행)을 미리 보여주는 메서드

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [9]:
df.info() # df.info() : 데이터의 구조와 상태에 대한 핵심 정보를 요약해서 보여주는 메서드 
          # Non-Null Count: "Null이 아닌 값", 즉 결측치(Missing Value)가 아닌 유효한 데이터의 개수를 의미 -> 중요함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df.describe() # df.describe() : 기본 통계지표들이 계산되어 나오는 메서드

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [12]:
df.describe().T

              count      mean       std  min  25%   50%  75%  max
sepal.length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal.width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal.length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal.width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5

In [ ]:
df.iloc[:,:-1] # df.iloc[행위치, 열위치] : 해당 행위치 , 열위치에 해당하는 데이터만 가져오는 메서드

     sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [20]:
y = df.iloc[:,-1]

In [21]:
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [ ]:
col = ['sepal.length','sepal.width','petal.length','petal.width'] # 위 방식이 어려우면 이렇게 사용해도 됨
df[col]

     sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [25]:
data = df.iloc[:,:-1].values
data.shape

(150, 4)

In [26]:
y = df.iloc[:,-1]

In [27]:
y.shape, type(y)

((150,), pandas.core.series.Series)

In [ ]:
# p.109
# Data Wrangling : Raw Data를 분석하기 좋은 형태로 다듬는 모든 과정

In [ ]:
# p.112 - 안 중요
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
# p.113 - 안 중요
d = {
    'a':1,
    'b':2,
    'c':3
}

pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [ ]:
# p. 114 - 중요

In [35]:
# p.115 - 안 중요
d = {
    'a':1,
    'b':2,
    'c':3
}

pd.Series(d)

a    1
b    2
c    3
dtype: int64

In [38]:
df = pd.DataFrame({'d1':d,'d2':d})

In [39]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [40]:
df.columns

Index(['d1', 'd2'], dtype='object')

In [ ]:
# p.117
df['d1'] # 첫번째 열만 가져오기

a    1
b    2
c    3
Name: d1, dtype: int64

### p.119 - 별표..중요함

In [ ]:
# p.119
df = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv') # 링크로 데이터 가져올 수도 있음
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [47]:
idx = pd.Index([1,2,3,4])

In [50]:
idx[3], idx[-1], idx[1:3]

(np.int64(4), np.int64(4), Index([2, 3], dtype='int64'))

In [52]:
idx.shape, idx.dtype

((4,), dtype('int64'))

In [ ]:
# p.120
# String, tuple, index 는 수정이 불가함
idx[0] = 999 # Index does not support mutable operations

TypeError: Index does not support mutable operations

In [ ]:
s = 'hello'
s[0] = "H" # 'str' object does not support item assignment

TypeError: 'str' object does not support item assignment

In [57]:
t = (1,2,3)
t[0] = 999 # 'tuple' object does not support item assignment

TypeError: 'tuple' object does not support item assignment

In [ ]:
idx1 = pd.Index([1,3,5,6,9])
idx2 = pd.Index([2,3,5,7,11])

idx1.intersection(idx2) # 교집합

Index([3, 5], dtype='int64')

In [ ]:
idx1.union(idx2) # 합집합

Index([1, 2, 3, 5, 6, 7, 9, 11], dtype='int64')

In [ ]:
# p.124
df = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [64]:
col1 = df['sepal.length']
type(col1)

pandas.core.series.Series

In [65]:
col1 = df['sepal.length']
col2 = df['sepal.width']
pd.DataFrame({'sepal.length':col1,'sepal.width':col2})

     sepal.length  sepal.width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [70]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width','variety'] # col 이름 바꾸기

In [71]:
df.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
# p. 126 새로운 col 만들기 -> 기존데이터를 가공해서 유의미한 새로운 정보를 만들어내기

df['aaa'] = df['sepal_length']-df['sepal_width']

In [73]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width variety  aaa
0           5.1          3.5           1.4          0.2  Setosa  1.6
1           4.9          3.0           1.4          0.2  Setosa  1.9
2           4.7          3.2           1.3          0.2  Setosa  1.5
3           4.6          3.1           1.5          0.2  Setosa  1.5
4           5.0          3.6           1.4          0.2  Setosa  1.4